### PR TITLE
feat: adds zksync era testnet

### PR DESCRIPTION
**Pull request by uF4No**
- Adds zksync era tesnet
- Updates public RPC urls for both zksync era mainnet and testnet

### CODE REVIEW

**Comment by pranavdaa** [comment]
Verified the changes. Looks good to me. @saihaj can u please release this in the next cli version release

**Review by saihaj — APPROVED** [review]
thank you!

**Comment by cryptoliang** [comment]
Hi, in the list of [supported networks](https://thegraph.com/docs/en/developing/supported-networks/), the network name for zksync testnet is `zksync2-testnet`, not `zksync-era-testnet`, could you please confirm which one is correct? @uF4No 

image

**Comment by azf20** [comment]
hey @cryptoliang pushing changes to align around the `zksync-era-testnet` name, as in this original PR

**Pull request merged**
