### PR TITLE
update NETWORK_SUBGRAPH_MAINNET & add `api-key` to CLI

### PR DESCRIPTION
**Pull request by DenisCarriere**
fixes: https://github.com/graphprotocol/graph-tooling/issues/1753

## CLI changes
- add `--api-key`: The API key to use for the Subgraph queries.

**Example**
```
graph publish --subgraph-id 5zvR82QoaXYFyDEKLZ9t6v9adgnptxYpKpSbxtgVENFV --api-key <STUDIO API KEY>
```

## Website changes
- replace `NETWORK_SUBGRAPH_MAINNET` with https://gateway.thegraph.com/api/{api-key}/subgraphs/id/DZz4kDTdmzWLWsV373w2bSmoar3umKKH9y82SUKr5qmp
- replace `NETWORK_SUBGRAPH_SEPOLIA` with https://gateway.thegraph.com/api/{api-key}/subgraphs/id/3xQHhMudr1oh69ut36G2mbzpYmYxwqCeU6wwqyCDCnqV
- perform requests using decentralized network with Studio Subgraph API Key `?apiKey=<STUDIO API KEY>`
- Add notification in case `apiKey` is not provided in URL params

### CODE REVIEW

**Comment by YaroShkvorets** [comment]
After looking into it I feel like the proper way would be to use `graph auth` to store the gateway API key. 
There already exists `graph auth` to store the deploy key for Studio. So introducing a separate flag just for `publish` seems wrong.

`graph auth` used to have `--studio` and `--hosted` flags. After removing Hosted service we removed both flags, so now it's only used storing Studio key

In Studio it actually tells you to using `--studio`, which doesn't work:

image

I suggest returning `--studio` flag to `graph auth` and also adding `--gateway` flag that would be used to store the gateway API key.

What do you think @alex-pakalniskis @0237h @DenisCarriere ?

**Comment by 0237h** [comment]
Good point, I think it makes sense to have all API keys managed from a single command like `auth`.

**Comment by 0237h** [comment]
> I propose returning --studio flag to graph auth and also adding --gateway flag that would be used to store the gateway API key.

@YaroShkvorets I'm wondering, aren't those technically the same keys ?
Is there a technical reason you need to use different keys or could users use the same for both and this is more of an option ?

@DenisCarriere qualifies the gateway key as just the *studio* API key and from what I understand it is also treated as such on the Explorer (see pic)
screenshot_2024-11-20_11-57-33

**Comment by YaroShkvorets** [comment]
These are different keys.
The key to publish subgraphs is sent to `https://api.thegraph.com`. It's assigned to you by the Studio and it's not used for anything else.
The key to sent queries is sent to `https://gateway.thegraph.com` and you can manage/rotate it.

BTW looks like the website is still making some requests to the Network subgraph when you run `graph publish` with `--subgraph-id` flag to edit an existing one. Not sure where it's coming from. Need to fix that too.

image

**Comment by YaroShkvorets** [comment]
1. make `--api-key` required for `graph publish`
2. figure out where network subgraph queries come from and replace with correct network subgraph url

**Comment by YaroShkvorets** [comment]
Added version extraction from network subgraph for an existing subgraph to properly update metadata.

**Review by YaroShkvorets — APPROVED** [review]

**Pull request merged**
