### PR TITLE
Port Graph CLI from commander.js to gluegun

### PR DESCRIPTION
**Pull request by Jannis**
I have not been too happy with commander.js since the moment we created Graph CLI.

Now that we have decided to make `graph init` interactive, I thought it would be a good time to move away from it and use https://infinitered.github.io/gluegun/ instead.

This PR does exactly that. All commands and some of the tools (like the compiler and type generator) are updated to Gluegun and its so-called _toolbox_. This not only makes logging less fragile, it also makes the output a bit prettier and introduces visual spinners for different steps of the commands (especially those that can run longer, like compiling or making HTTP requests).

Flags like `--verbose` or `--debug` are no longer needed but also don't break anything.

## Help output

```
➜  ~ graph --help
graph version 0.7.3

  graph         -
  version (v)   Output the version number
  remove        Unregisters a subgraph name
  init          Creates a new subgraph with basic scaffolding
  deploy        Deploys the subgraph to a Graph node
  create        Registers a subgraph name
  codegen       Generates AssemblyScript types for a subgraph
  build         Builds a subgraph and (optionally) uploads it to IPFS
  auth          Sets the access token to use when deploying to a Graph node
  help (h)      -

```
```
➜  ~ graph remove --help

graph remove [options] <subgraph-name>

Options:

      --access-token <token>
                            Graph access token
  -h, --help                Show usage information
  -g, --node <url>          Graph node to create the subgraph in

```
```
➜  ~ graph init --help

graph init [options] <subgraph-name>

Options:

  -h, --help                Show usage information
      --allow-simple-name   Use a subgraph name without a prefix component (default: false)

```
```
➜  ~ graph deploy --help

graph deploy [options] <subgraph-name> [<subgraph-manifest>]

Options:

      --access-token <token>
                            Graph access token
  -g, --node                Graph node to deploy the subgraph to
  -h, --help                Show usage information
      --ipfs <node>         Upload build results to an IPFS node
  -o, --output-dir <path>   Output directory for build results (default: build/)
  -w, --watch               Regenerate types when subgraph files change (default: false)

```
```
➜  ~ graph create --help

graph create [options] <subgraph-name>

Options:

      --access-token <token>
                            Graph access token
  -h, --help                Show usage information
  -g, --node <url>          Graph node to create the subgraph in

```
```
➜  ~ graph codegen --help

graph codegen [options] [<subgraph-manifest>]

Options:

  -h, --help                Show usage information
  -o, --output-dir <path>   Output directory for generated types (default: generated/)
  -w, --watch               Regenerate types when subgraph files change (default: false)

```
```
➜  ~ graph build --help

graph build [options] [<subgraph-manifest>]

Options:

  -h, --help                Show usage information
      --ipfs <node>         Upload build results to an IPFS node
  -o, --output-dir <path>   Output directory for build results (default: build/)
  -t, --output-format <format>
                            Output format for mappings (wasm, wast) (default: wasm)
  -w, --watch               Regenerate types when subgraph files change (default: false)

```
```
➜  ~ graph auth --help

graph auth [options] <node> <access-token>

Options:

  -h, --help                Show usage information

```

## Command output

image

## Visual progress

kapture 2019-02-21 at 15 56 43

### CODE REVIEW

**Comment by leodasvacas** [comment]
`-i` used to be short for `--ipfs`, which is not the case in this PR. Was that an accident?

**Comment by Jannis** [comment]
@leodasvacas Good point, yes, that was by mistake. I'll add it back. How's everything else looking?

**Comment by leodasvacas** [comment]
Also I think we used to default the IPFS port to `5001` if no port was provided. I'm testing out the branch and making comments as I go, haven't looked at the code yet.

**Comment by Jannis** [comment]
@leodasvacas `-i` (and also `-o`, which I missed in a few places) have been added back. I checked master for port `5001` but it looks like we didn't default to it anywhere: https://github.com/graphprotocol/graph-cli/search?utf8=%E2%9C%93&q=5001&type=

**Review by leoyvens — APPROVED** [review]
All the commands I tested work, new graphics are fun and the code structure is also much improved. Awesome!

**Pull request merged**
